In [1]:
import numpy as np

In [2]:
list1 = [1,2,3,4,5,6]
arr1 = np.array(list1)
arr1

array([1, 2, 3, 4, 5, 6])

In [3]:
list2 = list(range(10))
list2
arr2 = np.array(list2)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr3 = np.array(10) # 0D array
arr3

array(10)

In [6]:
arr4 = np.array(range(10)) #1D array
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr4[1]

1

In [35]:
arr5 = np.array([[1, 2, 3], [4, 5, 6]],dtype = int) # 2D array
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr6 = np.array([range(10), range(10),range(10)]) # 2D array
arr6

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [10]:
arr7 = np.array([[range(10), range(10)],[range(10), range(10)]])
arr7.ndim

3

In [11]:
arr8 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr8

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
arr8[1][1]

array([10, 11, 12])

In [15]:
arr5[1]

array([4, 5, 6])

In [21]:
arr9 = np.array(range(10), ndmin=5)
arr9

array([[[[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]]]])

In [26]:
# np.save("save_1",arr9)
arr10 = np.load("save_1"+".npy")
arr10

array([[[[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]]]])

In [36]:
np.savetxt("save_1.txt",arr5,delimiter = "\t")
arr11 = np.loadtxt("save_1.txt")
arr11

array([[1., 2., 3.],
       [4., 5., 6.]])