In [1]:
import numpy as np
import pandas as pd

In [2]:
 s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [3]:
s.dropna(inplace = True)
s

0    1.0
1    3.0
2    5.0
4    6.0
5    8.0
dtype: float64

In [4]:
dates = pd.date_range("20130101", periods=6)
# print(dates)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [5]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
print(df)

                   A         B         C         D
2013-01-01  0.138098  0.001469  1.428136 -0.480740
2013-01-02 -1.484050  0.795454  0.423890  0.734881
2013-01-03 -2.344404  1.100718 -0.235809  0.910245
2013-01-04  1.157449 -1.552835  0.571136  0.810869
2013-01-05 -1.343878  0.775791 -0.272268  0.603014
2013-01-06 -0.681017  0.106777  0.222453  2.182258


In [6]:
print(np.random.randn(6, 4)) # (row,column)
print(list("tran vo phuong duy"))


[[ 0.75567304 -1.40463249  0.70813614  0.51994506]
 [-2.06661464 -1.66522555  1.58552391 -0.04222575]
 [ 1.44302225  1.19848957  0.6793296  -1.00951125]
 [ 0.36282902 -0.69778774 -1.73768362 -0.47930582]
 [ 0.79905299  0.37078698 -0.34769135 -1.06575931]
 [-0.52550382  0.34421013 -0.68328028 -0.48995011]]
['t', 'r', 'a', 'n', ' ', 'v', 'o', ' ', 'p', 'h', 'u', 'o', 'n', 'g', ' ', 'd', 'u', 'y']


In [7]:
df2 = pd.DataFrame({
                                    "A": 1.0,
                                    "B": pd.Timestamp("20130102"),
                                    "C": pd.Series(1, index=list(range(4)), dtype="float32"),
                                    "D": np.array([3] * 4, dtype="int32"),
                                    "E": pd.Categorical(["test", "train", "test", "train"]),
                                    "F": "foo",
                                    }
                                )
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [8]:
print(pd.Timestamp("20210525 071218"))
print(list(range(4)))
print(np.array([3]* 4, dtype="int32"))

2021-05-25 07:12:18
[0, 1, 2, 3]
[3 3 3 3]


In [9]:
df2.dtypes # xem kiểu dữ liệu các cột

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [10]:
df.head(2)

A         B         C         D
2013-01-01  0.138098  0.001469  1.428136 -0.480740
2013-01-02 -1.484050  0.795454  0.423890  0.734881

In [11]:
df.tail(2)

A         B         C         D
2013-01-05 -1.343878  0.775791 -0.272268  0.603014
2013-01-06 -0.681017  0.106777  0.222453  2.182258

In [12]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [13]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [14]:
df.to_numpy()

array([[ 1.38097689e-01,  1.46881539e-03,  1.42813592e+00,
        -4.80739834e-01],
       [-1.48405014e+00,  7.95454137e-01,  4.23890205e-01,
         7.34881420e-01],
       [-2.34440369e+00,  1.10071833e+00, -2.35809234e-01,
         9.10245162e-01],
       [ 1.15744875e+00, -1.55283523e+00,  5.71136020e-01,
         8.10869445e-01],
       [-1.34387779e+00,  7.75790740e-01, -2.72267879e-01,
         6.03013865e-01],
       [-6.81017077e-01,  1.06776521e-01,  2.22453211e-01,
         2.18225845e+00]])

In [15]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [16]:
df.describe() #shows a quick statistic summary of your data:

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.759634  0.204562  0.356256  0.793421
std    1.254187  0.961021  0.626604  0.849234
min   -2.344404 -1.552835 -0.272268 -0.480740
25%   -1.449007  0.027796 -0.121244  0.635981
50%   -1.012447  0.441284  0.323172  0.772875
75%   -0.066681  0.790538  0.534325  0.885401
max    1.157449  1.100718  1.428136  2.182258

In [17]:
df.T

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.138098   -1.484050   -2.344404    1.157449   -1.343878   -0.681017
B    0.001469    0.795454    1.100718   -1.552835    0.775791    0.106777
C    1.428136    0.423890   -0.235809    0.571136   -0.272268    0.222453
D   -0.480740    0.734881    0.910245    0.810869    0.603014    2.182258

In [18]:
df

A         B         C         D
2013-01-01  0.138098  0.001469  1.428136 -0.480740
2013-01-02 -1.484050  0.795454  0.423890  0.734881
2013-01-03 -2.344404  1.100718 -0.235809  0.910245
2013-01-04  1.157449 -1.552835  0.571136  0.810869
2013-01-05 -1.343878  0.775791 -0.272268  0.603014
2013-01-06 -0.681017  0.106777  0.222453  2.182258

In [19]:
df.sort_values(by="B")

A         B         C         D
2013-01-04  1.157449 -1.552835  0.571136  0.810869
2013-01-01  0.138098  0.001469  1.428136 -0.480740
2013-01-06 -0.681017  0.106777  0.222453  2.182258
2013-01-05 -1.343878  0.775791 -0.272268  0.603014
2013-01-02 -1.484050  0.795454  0.423890  0.734881
2013-01-03 -2.344404  1.100718 -0.235809  0.910245

In [20]:
df.sort_index(axis=1, ascending=False)

D         C         B         A
2013-01-01 -0.480740  1.428136  0.001469  0.138098
2013-01-02  0.734881  0.423890  0.795454 -1.484050
2013-01-03  0.910245 -0.235809  1.100718 -2.344404
2013-01-04  0.810869  0.571136 -1.552835  1.157449
2013-01-05  0.603014 -0.272268  0.775791 -1.343878
2013-01-06  2.182258  0.222453  0.106777 -0.681017

In [21]:
df["A"]

2013-01-01    0.138098
2013-01-02   -1.484050
2013-01-03   -2.344404
2013-01-04    1.157449
2013-01-05   -1.343878
2013-01-06   -0.681017
Freq: D, Name: A, dtype: float64

In [22]:
df[0:3] # [row:row]

A         B         C         D
2013-01-01  0.138098  0.001469  1.428136 -0.480740
2013-01-02 -1.484050  0.795454  0.423890  0.734881
2013-01-03 -2.344404  1.100718 -0.235809  0.910245

In [23]:
df["20130102":"20130104"]# [row:row]

A         B         C         D
2013-01-02 -1.484050  0.795454  0.423890  0.734881
2013-01-03 -2.344404  1.100718 -0.235809  0.910245
2013-01-04  1.157449 -1.552835  0.571136  0.810869